### ISSUE TITLE
problems in the loss functions

### ISSUE THREAD

**Issue by xzyaoi** [k3nt0w/chainer_fcn#1]
Hi, 

When I try to run your program with image size = 256, it went to a problem saying that:

```
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    loss = model(x, y, train=True)
  File "/media/sfermi/Programming/research/cv/capsuleNet/segCaps-chainer/model.py", line 90, in __call__
    loss = F.softmax_cross_entropy(h, t)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/functions/loss/softmax_cross_entropy.py", line 381, in softmax_cross_entropy
    normalize, cache_score, class_weight, ignore_label, reduce)(x, t)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/function.py", line 344, in forward
    return self.forward_cpu(inputs)
  File "/home/sfermi/.local/share/virtualenvs/segCaps-chainer-QBC-0MaY/lib/python3.5/site-packages/chainer/functions/loss/softmax_cross_entropy.py", line 94, in forward_cpu
    log_p = log_yd[numpy.maximum(t.ravel(), 0), numpy.arange(t.size)]
IndexError: index 220 is out of bounds for axis 0 with size 21

```

I tried to use different size of image like 32*32, but the problem still exists. 

```
IndexError: index 38 is out of bounds for axis 0 with size 21
```

**Comment by xzyaoi** [comment]
Found it is because I accidentally convert the original image to gray scale. Sorry to bother.
